### PR TITLE
Remove documents folder

### PR DESCRIPTION
**Pull request by hursey013**
This is now in `.gitignore` so removing from repo.

### CODE REVIEW

**Comment by zachmargolis** [comment]
Wait did the PDF get moved into the styleguide?

**Comment by hursey013** [comment]
Yeah @gemfarmer had moved it in previously, likely with the intent to centralize all assets. I'm not sure that this PDF would probably ever be shared with the app, but may there is a use case for having PDFs like these cataloged in the style guide? What do you think?

**Comment by zachmargolis** [comment]
I think this particular PDF, I'd leave in the marketing site only (since if we did reference it in the IDP, we'd just link to the marketing site anyways)

**Comment by hursey013** [comment]
Yeah that makes sense, I can sort it out in another PR.

**Comment by zachmargolis** [comment]
sounds good! thanks

**Pull request merged**
