### PR TITLE
Remove layouts section

### PR DESCRIPTION
**Pull request by aduth**
**Why**: The layouts are overly prescriptive, may fall (or have fallen) out of alignment with current recommendations, and are not the most useful of resources for referencing appearance or markup of page sections (footer, navigation, etc).

This removal should be complemented by future work to either:
- Reference base components from USWDS for additional guidance
- Document and list differences between USWDS footer / navigation and the login.gov Design System

### CODE REVIEW

**Review by zachmargolis — APPROVED** [review]
LGTM

**Review by juliaelman — CHANGES_REQUESTED** [review]
We are wanting to remove this from the main navigation too, correct?

**Comment by aduth** [comment]
> We are wanting to remove this from the main navigation too, correct?

Yeah, it should be removed with the changes here:

https://github.com/18F/identity-style-guide/pull/179/files#diff-833e7bb7ade39092fdeebe1d54db3a3ed970610ebe49e3b97f5e59da91c04edd

Are you still seeing it in the branch?

**Comment by juliaelman** [comment]
Weird! It is gone now 🚀

**Review by juliaelman — APPROVED** [review]

**Pull request merged**
