### PR TITLE
Add combo box input styling

### PR DESCRIPTION
**Pull request by orenyk**
See https://github.com/18F/identity-site/pull/923

### CODE REVIEW

**Comment by aduth** [comment]
Is this what it's expected to look like after the styling? (https://federalist-17bd62cc-77b7-4687-9c62-39b462ce6fd5.app.cloud.gov/preview/18f/identity-site/oyk-partner-contact/partners/contact/)

image

image

I'd like for @nickttng to take a look at this. I could see how it'd be good to have some baseline styles in place to have consistency among the inputs for a component we may not have been supporting very well before, but I expect Nick will at least want to incorporate it into our Figma resources (and maybe even customize it further).

**Comment by nickttng** [comment]
Visual styling: It looks very close to what I have in mind. 

If there are any iterations, it is to extend the hovering border to the edge, as USWDS has done with theirs (See side-by-side examples below). The spacing between the hovering border and outer border makes the hovered element somewhat misaligned. This is not a blocker, so it's something we can iterate more in Figma and update the combo box after this PR.

| LGDS | USWDS |
|---|---|
| combo-box-lgds-v01 | combo-box-uswds |

Functionally, it seems to work as expected. Tested with VoiceOver as well.

**Comment by orenyk** [comment]
@aduth that looks right to me! and re: @nickttng's feedback about the hover border - I defer to you all on when/how to merge this in - I just wanted to share the changes that _seemed_ to work on the partner site and let you take it from there 😄. Thanks!

**Comment by aduth** [comment]
@orenyk I appreciate you taking the step to backport this to the design system! I created a ticket at LG-7270 to track completing this work based on Nick's comments, and since we'll probably also want to add a basic documentation page for the component (consistent with other components we've styled).

I'll plan to leave this open 'til that can be worked on, but based on [discussion in yesterday's LGDS Office Hours](https://docs.google.com/document/d/10b7Gis_VxYT3roR01MX4hwPa6-Tq29YBaLPIB3vWnUw/edit#heading=h.vkrgqzaulyw), you should be good to go with the changes you've added in https://github.com/18F/identity-site/pull/923 .

**Comment by orenyk** [comment]
@aduth my pleasure! Feel free to build off of this branch or close/delete whenever you're ready. Thanks for all of your help!

**Comment by aduth** [comment]
This has diverged quite a bit from `main`. Let's pick it up again later. This is tracked at [LG-7270](https://cm-jira.usa.gov/browse/LG-7270).

**Pull request closed without merging**
