### PR TITLE
Remove accessibility policies page

### PR DESCRIPTION
**Pull request by aduth**
As of #178, the "Accessibility" top-level page was removed. This left a subpage "Accessibility Policies" no longer linked to, but it still exists in the site:

https://design.login.gov/accessibility/policies/

The proposed changes here adapt the content of this page to a new "Images" page, to include guidance on how login.gov uses illustration, how those illustrations should often be considered decorative, and accessibility recommendations for marking up those images accordingly.

**Live preview URL:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-remove-a11y-policies/images/

**Screenshot:**

images page screenshot

### CODE REVIEW

**Review by juliaelman — CHANGES_REQUESTED** [review]
We should keep this content, as the USWDS does not provide accessibility guidance for decorative imagery. Login.gov uses illustration to help guide users and it would be good to provide guidance on how to make those accessible. 

Would love to hear your ideas of where you think this content should live.

**Comment by aduth** [comment]
>Login.gov uses illustration to help guide users and it would be good to provide guidance on how to make those accessible.

That makes sense in the context of how we apply decorative images specifically in our products. I was originally considering removal mostly in treating existing resources like the [W3C _Decorative Images_ article](https://www.w3.org/WAI/tutorials/images/decorative/) as more canonical and up-to-date.

>Would love to hear your ideas of where you think this content should live.

I recall a suggestion that we may still have reason to have an "Accessibility" top-level page in the design system website, but tailored more specifically to these sorts of practical guidance.

Maybe we could restore the "Accessibility" page, with a short introduction pointing to the [brochure site's accessibility statement](https://login.gov/accessibility/), and with the remainder of sections devoted to practical guidance like this?

**Comment by juliaelman** [comment]
> > Login.gov uses illustration to help guide users and it would be good to provide guidance on how to make those accessible.
> 
> That makes sense in the context of how we apply decorative images specifically in our products. I was originally considering removal mostly in treating existing resources like the [W3C _Decorative Images_ article](https://www.w3.org/WAI/tutorials/images/decorative/) as more canonical and up-to-date.
> 
> > Would love to hear your ideas of where you think this content should live.
> 
> I recall a suggestion that we may still have reason to have an "Accessibility" top-level page in the design system website, but tailored more specifically to these sorts of practical guidance.
> 
> Maybe we could restore the "Accessibility" page, with a short introduction pointing to the [brochure site's accessibility statement](https://login.gov/accessibility/), and with the remainder of sections devoted to practical guidance like this?

🤔 the direction we discussed heading was to have more inline, contextual guidance around accessibility when it comes to the design system. for example, i could see us creating an "illustration" or "images" section and have guidance under there.

@nickttng @anniehirshman-gsa would love your thoughts too!

**Comment by zachmargolis** [comment]
> We should keep this content, as the USWDS does not provide accessibility guidance for decorative imagery. Login.gov uses illustration to help guide users and it would be good to provide guidance on how to make those accessible.

Just to clarify.... what I think @juliaelman is saying is that we need to explicitly document this policy somewhere because when a partner ran an accessibility audit against us they reported a ton of missing alt tags. So to pass that audit we needed to explicitly document that *somewhere* and looking at the brochure site accessibility page, I think that's a fine destination

> 🤔 the direction we discussed heading was to have more inline, contextual guidance around accessibility when it comes to the design system. for example, i could see us creating an "illustration" or "images" section and have guidance under there.

In general I like the idea of having stuff inline where it's useful but I think having a clear section on our clear accessibility page makes it easier to find this particular information when somebody is auditing us for it?

**Comment by zachmargolis** [comment]
Also this reminds me, maybe we should get input from @shawnique and @TiffanyAndrews on where the content lives (or how we link to it), since they helped us run the last accessibility audit, the one that resulted in our need to document our decorative image policy in the first place

**Comment by juliaelman** [comment]
Sounds like we need to raise the communication bandwidth on this 🤔 I'll add to the agenda for an upcoming UX Huddle so we can have a sync conversation with everyone instead of in GH comments 😄 (more inclusive)

**Comment by juliaelman** [comment]
Discussed in our huddle. @aduth is going to update this PR (or create a new PR, whatever you think makes more sense!) so that this content lives within our system to include image accessibility guidance.

**Comment by aduth** [comment]
I pushed an update which introduces a new "Images" top-level page:

https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-remove-a11y-policies/images/

From the updated pull request description:

>The proposed changes here adapt the content of this page to a new "Images" page, to include guidance on how login.gov uses illustration, how those illustrations should often be considered decorative, and accessibility recommendations for marking up those images accordingly.

I'd welcome any feedback on the content or structure of the page (cc @Danielle-Lee @cannandev).

Live preview URL: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-remove-a11y-policies/images/

**Comment by cannandev** [comment]
Looks great as a top level item! 

Seeing it now, as a top level item, makes it stand out as one of our _principles_. I prefer this approach than  listing **Images** under **Components**, which are really samples of code -- not principles.

**Comment by Danielle-Lee** [comment]
Can we make a content edit to this sentence? (last sentence, first paragraph under Accessibility Guidance) 

Current: To help prevent confusing, redundant and/or tedious experience, we at Login.gov have set decorative images to be hidden from screen readers.

Proposed change:  We set decorative images as "hidden" from screen readers to help prevent a confusing, redundant and/or a tedious experience.

**Comment by aduth** [comment]
Thanks @cannandev @Danielle-Lee ! I updated the text in 3916b23. I agree it reads much better this way. Thanks.

**Comment by juliaelman** [comment]
@aduth great work. What do you think about moving the content here to our new "Images" section: https://design.login.gov/brand/#illustration

And then removing it from the `Brand` section completely.

**Comment by aduth** [comment]
> @aduth great work. What do you think about moving the content here to our new "Images" section: https://design.login.gov/brand/#illustration
> 
> And then removing it from the `Brand` section completely.

@juliaelman Yeah, I think it could make sense, at least as far as avoiding fragmentation of guidance around illustration. If I recall correctly, was there also some desire to do away with the "Brand" page entirely as well? The only reservation I might have is that the use of illustration as it relates to brand could still be relevant. But if we plan to move out more of the Brand content, it does feel like Images would be the best spot for this illustration guidance.

**Comment by juliaelman** [comment]
@aduth @cannandev I've updated the images page to include some introductory content (71f041d), as well as removed an image we are no longer using in the product (0ff6281).

**Comment by juliaelman** [comment]
> @juliaelman Yeah, I think it could make sense, at least as far as avoiding fragmentation of guidance around illustration. If I recall correctly, was there also some desire to do away with the "Brand" page entirely as well? The only reservation I might have is that the use of illustration as it relates to brand could still be relevant. But if we plan to move out more of the Brand content, it does feel like Images would be the best spot for this illustration guidance.

Following up here. We talked about leaving `Brand` in the design system for now and that we will create a press kit section on login.gov (footer). I'll create a ticket for that so we can track that work.

**Comment by aduth** [comment]
Looks good and reads well to me 👍

**Comment by cannandev** [comment]
@juliaelman LGTM! What do you think about changing **Accessibility Guidelines** to **Be accessible**? Am I going overboard with the alliterations?

**Comment by juliaelman** [comment]
@cannandev I think that is a great idea! Updated here 17f7c17

**Review by juliaelman — APPROVED** [review]
🚀

**Pull request merged**
